ChargePoint/buildroot

package/freescale-imx/imx-gpu-viv/imx-gpu-viv.hash
package/freescale-imx/imx-gpu-viv/imx-gpu-viv.mk

This version works with the 4.14.98_2.3.0 kernel drivers.
Signed-off-by: Michael Fairman <michael.fairman@chargepoint.com>

imx-gpu-viv: bump version to 6.2.4.p4.8

---

fs/common.mk

The fakeroot script does not appear to be used in any of the checked
in defconfig targets, but it seems that most often the post
fakeroot script should be done after all the packages rules have
been applied instead of before.
Given that a change in systemd moved the SYSTEMD_PRESET_ALL hook to
a ROOTFS_PRE_CMD_HOOKS, there was no way to use a FAKEROOT script
to disable a service or fixup a systemd configuration. The systemd
move makes sense, and this just tries to preserve the same ability
to fixup a rootfs after all the cmd hooks are processed.
Refer to commit 65b63785a642bbc565924edf365b5d7c080f961c for
the change that instigated this reordering.

fs/common.mk: move BR2_ROOTFS_POST_FAKEROOT_SCRIPT after pre cmd hooks

---

package/psplash/psplash-start.service

Because of the way the code is being bundled, the psplash unit
might run on a headless environment in development or in a fully
assembled fixture for a display.
This just suppresses the somewhat annoying restart loop during
startup:
[FAILED] Failed to start Starts Psplash Boot screen.
See 'systemctl status psplash-start.service' for details.

package/psplash: address that psplash might run with no framebuffer

---

package/uboot-tools/0004-tools-add-force-read-pem-flag-to-mkimage.patch

In some cases an openssl engine implemented by an HSM vendor will
use keys and certs stored directly on the filesystem.  For example
AWS CloudHSM needs a fake pem file which contains a reference to
the acutal private key stored in the HSM.
This change adds a command line argument (-m) that forces the
logic that eads pem files to be used even if an openssl engine
is specified when signing a FIT image.
$ mkimage -m -k /path/to/keys -N cloudhsm -F /path/to//file.itb

packages/uboot-tools: add force read pem flag to mkimage

---

package/dhcp/dhcp.mk

In a readonly fs configuration the skeleton-init-fs will move
the var directories to the usr/share/factory and the run a command
like this:
mv $(TARGET_DIR)/var $(TARGET_DIR)/usr/share/factory/var
mkdir -p $(TARGET_DIR)/var
for i in $(TARGET_DIR)/usr/share/factory/var/* \
$(TARGET_DIR)/usr/share/factory/var/lib/* \
$(TARGET_DIR)/usr/share/factory/var/lib/systemd/*; do
If the symlink is to the /tmp directory the glob compare on the
dhcp link will evaluate and result in an incorrect entry being
created in the resulting tmpfs mount on var.
L+! /var/lib/dhcp - - - - ../usr/share/factory//var/lib/dhcp
So, make the link relative and the result of the configuration
doesn't get impacted.

package/dhcp: fix dhcp symlink in target/var/lib/dhcp

---

boot/uboot/uboot.mk

The the logfile "u-boot-dtb.imx.log " contains information
required by the Code Signer Tool to correctly sign the
image and perform validation during bootup. This file
is being added to the build so it can be consumed when
a given build is to be signed.
Example contents:
$ cat u-boot-dtb.imx.log
Image Type:   Freescale IMX Boot Image
Image Ver:    2 (i.MX53/6/7 compatible)
Mode:         DCD
Data Size:    495616 Bytes = 484.00 KiB = 0.47 MiB
Load Address: 177ff420
Entry Point:  17800000
HAB Blocks:   177ff400 00000000 00074c00
DCD Blocks:   00910000 0000002c 00000300

boot/uboot: add u-boot-dtb.imx.log as target

---

package/freescale-imx/imx-sc-firmware/imx-sc-firmware.hash
package/freescale-imx/imx-sc-firmware/imx-sc-firmware.mk

Update imx-sc-firmware to latest 1.6.0 in sync with scfw
porting kit and Linux kernel 5.4.x. Also uploaded NXP source code tar file
as artifact on build server. its seems NXP link to imx-scfw is broken, so I downloaded 1.6.0
source code version from release and pull on build artifact server.

target/UCB: update imx-sc-firmware to latest 1.6.0

---

package/psplash/psplash-start.service
package/psplash/psplash-systemd.service

Recent systemd versions require RemainAfterExit for interdependent services to avoid
restarting the lower dependency, even if it's not marked for restart on exit.
From Yocto commit:
https://github.com/kraj/poky/commit/ce987c6ae867eb9b0850445d496fb01c5c6709a
JIRA PLAT-1133

targets: imx boot splash screens (psplash service)

---

package/sox/sox.mk

This patch installs the sox header file and shared library files to the staging folder during the build process. With this, the header and shared library files can be included.
JIRA : https://chargepoint.atlassian.net/browse/PLAT-1231

Packages: sox makefile update to install header and .so file

---

support/misc/Vagrantfile

The default vagrant downloads a buildroot tarball and builds that,
but for testing it is a bit more convenient to just use the shared
directory across the vagrant box against the checked out buildroot

support/misc: update the Vagrantfile to use the git checkout

---

package/raw2rgbpnm/0001-add-bggr12-format-and-bggr-workaround.patch

This update modified the bggr12 patch to include support for grbg12 and
includes support for generic high-aligned bit shifting (when data is
aligned to bit 16 and not bit 0).  In the IMX-isi case data is aligned to bit 14.
JIRA PLAT-1437

Packages: raw2rgbpnm - support for misaligned 12-bit GRBG debayering.

---

package/libwebsockets/libwebsockets.mk

changes:
* adds -DLWS_WITH_EXTERNAL_POLL=ON to support "external" event loops
* adds -DDISABLE_WERROR=ON to overcome a single warning on compile
Signed-off-by: Jeff Hart <jeffrey.hart@chargepoint.com>

libwebsockets:  extra CMAKE flags required for build of 4.2.0

---

package/unzip/unzip.mk

Buildroot always enable largefile support in the toolchains, and
thus the associated definitions are always on. This leads to a
problem in the unzip that on a 32-bit arch with these flags being
passed in
-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
But, the LARGE_FILE_SUPPORT not being defined will cause a size
mismatch on the comparison of the zipfiles.
$ unzip test.zip
Archive: test.zip
error: invalid zip file with overlapped components (possible zip bomb)
Simple solution is just enable LARGE_FILE_SUPPORT in cmake to get
an expected extraction.
[PLAT-1632]
[PLAT-1632]: https://chargepoint.atlassian.net/browse/PLAT-1632

package/unzip: configure with LARGE_FILE_SUPPORT by default

---

package/libwebsockets/libwebsockets.mk

LWS_WITH_EXTERNAL_POLL was set to support legacy code that relied on external event loop support. This code is no longer present.
Signed-off-by: David Leeds <david.leeds@chargepoint.com>

package/libwebsockets: disable LWS_WITH_EXTERNAL_POLL

---

package/psplash/0001-psplash_multiline_msg.patch

In order to display multiline messages on boot, such as hostname and
version, psplash has to be patched to allow a new line separator, as
newline is used to tokenize commands.  Added support for vertical-tabs.
Signed-off-by: Matthew Hungerford <mhungerford@gmail.com>

package/psplash: repair support for multiline messages on bootsplash

---

package/systemd/Config.in
package/systemd/systemd.mk

systemd-resolved has a single hardlink set to compat mode which does not allow
for features such as DNS caching and other fun things.  This choice allows the
hard-link to be changed between a couple of operating modes, the default
(compat) and the more useful variant (stub, systemd recommended default) which
allows the resolver to act as a caching daemon.
Signed-off-by: Jeff Hart <jeffrey.hart@chargepoint.com>

systemd:  set options for resolver mode

---

package/modem-manager/Config.in
package/modem-manager/modem-manager.mk

ModemManager only allows AT commands to be sent over dbus if the --debug
flag is specified.  Add a config option to allow setting the
compile-time flag to allow the AT command interface outside of debug-only mode.

ModemManager: enable AT interface with bool flag

---

package/json-for-modern-cpp/json-for-modern-cpp.hash
package/json-for-modern-cpp/json-for-modern-cpp.mk

License file year changed to 2021.
Signed-off-by: Michael Nosthoff <buildroot@heine.tech>
[Arnout: update license hash]
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit d7f0a9bd932b5fee8541f0fbb2c83c6da09d0575)

package/json-for-modern-cpp: bump version to 3.10.2

---

package/dbus/dbus.hash
package/dbus/dbus.mk

Bump `dbus` package from 1.12.20 to 1.13.20. This includes a host of bug fixes and improvements, but the relevant change, is `dbus-send` gets a `--sender` option that enables it to send signals that D-Bus proxies won't filter out.

package/dbus: bump to version 1.13.20

---

package/cmake/cmake.hash
package/cmake/cmake.mk

In order to build tensorflow lite 2.6.0 using the cmake build system (the make build sytem is being deprecated), the cmake package included in buildroot needs to be updated; buildroot upstream has already upgraded buildroot to 3.16.9 which works well for tensorflow lite builds and seems fine for all other cmake builds we use (like emb-core).
Another thing tensorflow lite needs to build correctly is OpenSSL support has part of cmake since it uses `FetchContent` in order to fetch dependent packages (which in turn needs cmake itself to support HTTPS). It seems this was originally disabled in buildroot to avoid leaking dependencies to the host systems but from what I can tell, that no longer an issue.
(Getting a bit of a jump start on tensorflow lite integration as this is required but …

package/cmake: upgrade to 3.16.9 and enable openssl

---

package/systemd/Config.in
package/systemd/systemd.mk

The compatible flags for the init and rc directories are disabled
by default, so allow a configuration option to set the expected
paths to /etc/init.d and /etc respectively.
This allows a hybrid systemd approach as needed for startup

package/systemd: add configuration support for SysV compat

---

package/libwebsockets/libwebsockets.hash
package/libwebsockets/libwebsockets.mk

Bump libwebsockets to v4.3.0 to pull in IPv6 fixes.
Signed-off-by: Jeffrey Hart <jeffrey.hart@chargepoint.com>

libwebsockets: bump to v4.3.0

---

package/freescale-imx/imx-seco/Config.in
package/freescale-imx/imx-seco/imx-seco.mk

Changes added to select ahab container image
for different imx8 socs including imx8dxl.
Signed-off-by: Aswath Gajendran <aswath.gajendran@chargepoint.com>

package/imx-seco: add choices for imx8 socs

---

package/psplash/psplash-systemd.service

The fifo is created from psplash-start and so only having a Requires lists the dependency on
psplash-start but not that this service needs to come after the start.
Requires=
Similar to Wants=, but declares a stronger requirement dependency.
Dependencies of this type may also be configured by adding a symlink
to a .requires/ directory accompanying the unit file.
If this unit gets activated, the units listed will be activated as
well. If one of the other units fails to activate, and an ordering
dependency After= on the failing unit is set, this unit will not be
started. Besides, with or without specifying After=, this unit will
be stopped (or restarted) if one of the other units is explicitly
stopped (or restarted).
Often, it is a better choice to use Wants= instead of Requires= in
order to …

package/psplash: add the start order for the psplash systemd

---

package/libwebsockets/libwebsockets.hash
package/libwebsockets/libwebsockets.mk

libwebsockets has fixed many bugs in v4.3.2, pull in new version to apply these fixes.

libwebsockets: update version from 4.3.0 to 4.3.2

---

package/python-intelhex/python-intelhex.mk

Zephyr build system depends on intelhex Python package.

package/python-intelhex: enable as host package

---

package/sdbus-cpp/sdbus-cpp.hash
package/sdbus-cpp/sdbus-cpp.mk

Changelog:
https://github.com/Kistler-Group/sdbus-cpp/releases/tag/v1.3.0
A trailing whitespace was removed in the COPYING-LGPL-Exception file, so the hash differs.
https://github.com/Kistler-Group/sdbus-cpp/commit/dcd9d46b9c5e5011dc7170e9d081bcf80096fd15
Signed-off-by: Sergey Bobrenok <bobrofon@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit 93556f95a3a8ce402eb29e8f5c73f0c02a708f54)

package/sdbus-cpp: bump to version 1.3.0

---

package/freescale-imx/firmware-sentinel/Config.in

There are 2 versions of the IMX93 SOM, A0 and A1. They need different AHAB containers to function properly.
This adds support to select the correct container.

fix(firmware-sentinel): add support for AHAB container A1
